# Frontend build stage
FROM node:21-alpine AS builder
WORKDIR /app
COPY frontend/ .
RUN npm install && npm run build

# Serve stage
FROM node:21-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist

EXPOSE 3000

ENV VITE_API_URL=https://placement-backend.onrender.com
CMD ["serve", "-s", "dist", "-l", "3000"]
