services:
  - type: web
    name: placement-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: placement-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          name: placement-backend
          property: renderURL
