services:
  # Backend API (Express)
  - type: web
    name: placement-prep-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/src/server.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        generateValue: false
      - key: JWT_SECRET
        generateValue: true

  # Frontend (Vite static site)
  - type: static
    name: placement-prep-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE
        value: https://placement-prep-backend.onrender.com/api


