services:
  - type: web
    name: placement-prep-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        generateValue: false
      - key: JWT_SECRET
        generateValue: true
  - type: static
    name: placement-prep-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://placement-prep-backend.onrender.com/api


