services:
  # Backend-only deployment
  - type: web
    name: placement-prep-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        generateValue: false
      - key: JWT_SECRET
        generateValue: true
